### ISSUE TITLE
커밋 Title 에 이름을 빼는건 어떨까요?

### ISSUE THREAD

**Issue by woin2ee** [ILGOB/Plinic-iOS#122]
커밋한 사람도 쉽게 확인할 수 있는것 같고 이름을 넣으니까 불필요하게 길어지는것 같아 빼면 여러모로 편리한게 있을것같은데 어떻게 생각하시나요

**Comment by blooper20** [comment]
(jaewoo/branch) 여기에서 
(branch)로 바꾸자는 얘기인가요??
만약 위에 예시가 맞다면 상관없을것 같습니다 생각보다 커밋 내용에 있는 이름으로 판별하기보단 프로필 사진으로 보는게 더 눈에 띄는거 같습니다!

**Comment by woin2ee** [comment]
확인~

**Comment by woin2ee** [comment]
확인~
